run:
  timeout: 2m
  output-format: colored-line-number

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - staticcheck
    - errcheck
    - unused

issues:
  exclude-use-default: false
